# Generated by Django 6.0.1 on 2026-03-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0016_medicaltest_testreport_testreportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
