# Generated by Django 6.0.3 on 2026-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0018_doctor_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receptionist_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='receptionist_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending Receptionist', 'Pending Receptionist'), ('Booked', 'Booked'), ('Arrived', 'Arrived'), ('Waiting', 'Waiting'), ('In Consultation', 'In Consultation'), ('Completed', 'Completed'), ('Missed', 'Missed'), ('Cancelled by Patient', 'Cancelled by Patient'), ('Cancelled by Doctor', 'Cancelled by Doctor')], default='Pending Receptionist', max_length=30),
        ),
    ]
