# Generated by Django 6.0.4 on 2026-04-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0019_appointment_receptionist_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_message_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_message_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
